'use client'
import '../styles/globals.css'
import {Inter} from 'next/font/google'
import {domAnimation, LazyMotion} from "framer-motion";
import {Toaster} from 'react-hot-toast';

const inter = Inter({subsets: ['latin']})

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <LazyMotion features={domAnimation}>
            <Toaster/>
            {children}

        </LazyMotion>
        </body>
        </html>
    )
}
